### ISSUE TITLE
上传问题

### ISSUE THREAD

**Issue by AberSheeran** [docblue/chfsgui#1]
在使用域名+Nginx反向代理1.0.1 GUI版本的时候，上传文件进度条到100%，但始终不提示上传成功。
直接使用域名+Port就可以正常使用。
系统：WindowsServer2012

**Comment by docblue** [comment]
能不能贴出你的.conf相关配置

**Comment by AberSheeran** [comment]
尝试了修改配置，最后发现把Nginx的`gzip on`注释掉才能上传成功。请问这个可能是因为什么呢？

**Comment by docblue** [comment]
抱歉我没有复现出来，没法帮你。建议翻翻日志看有无线索

**Comment by AberSheeran** [comment]
尝试了一下，发现手机和FireFox都可以。可能是我的Chrome某些设置的问题吧。
