### ISSUE TITLE
向一个2级目录，用拖放到页面的方式上传文档，不能存放在该2级目录，而是存放在了根目录下

### ISSUE THREAD

**Issue by tqjason** [docblue/chfsgui#22]
向一个2级目录，用拖放到页面的方式上传文档，不能存放在该2级目录，而是存放在了根目录下。
例如：想上传文件至 /abc/123/ ，在/abc/123/页面拖放单文件，文件上传后保存在了 /abc/下。
点击上传文件按钮，是正常的。

这应该是chfs.exe的一个问题，而不是chfsgui的问题，但是没有地方可以报chfs的bug，所以发在了这里。

**Comment by docblue** [comment]
请升级到V3.1
