### ISSUE TITLE
上传csv文件，下载下来变成了txt

### ISSUE THREAD

**Issue by lazygoat644** [docblue/chfsgui#24]
大佬你好，想问一下，我在远端服务器上传了一份从mysql扒下来的csv表格，上传到chfs服务器之后，在网页端显示的是csv格式，但是下载到本地端就会变为txt格式，想问一下这是触发了什么操作机制吗？谢谢！

**Comment by horizon86** [comment]
csv就是文本，你看看是不是没显示后缀默认用的记事本打开了

**Comment by lazygoat644** [comment]
> csv就是文本，你看看是不是没显示后缀默认用的记事本打开了

你好，我再次确认了一下，确实就是csv上传之后下载到本地变成了后缀为txt的文件，并不是我打开方式的问题。
平台macos bigsur 12.2.1，chrome 98.0.4758.80

**Comment by lazygoat644** [comment]
<img width="918" alt="iShot2022-02-23 21 43 27" src="https://user-images.githubusercontent.com/25381858/155331323-eab6be21-83d4-4943-9eed-92d355affd49.png">
<img width="1072" alt="iShot2022-02-23 21 43 49" src="https://user-images.githubusercontent.com/25381858/155331347-0087961d-1647-4296-9931-0117bf3caef8.png">

**Comment by docblue** [comment]
去官网试试v3.1
