### ISSUE TITLE
1.8版本mac 10.14.2不能运行

### ISSUE THREAD

**Issue by Jonnyan404** [docblue/chfsgui#3]
![image](https://user-images.githubusercontent.com/20352705/50074813-ffc33f80-0217-11e9-9f7c-737603cedf57.png)

**Comment by docblue** [comment]
请尝试下以root权限chmod 777 ./chfs 之后运行程序

**Comment by Jonnyan404** [comment]
![image](https://user-images.githubusercontent.com/20352705/50092552-66148600-0249-11e9-80b3-78bfd9ca6081.png)
