### ISSUE TITLE
大佬,可否完善一下 Linux/unix 下使用说明

### ISSUE THREAD

**Issue by Jonnyan404** [docblue/chfsgui#4]
## 上传问题
```
可以通过wget和curl进行上传和下载。比如将1.txt上传到logs文件夹中：curl http://192.168.1.11/upload -F "folder=logs" -F "file=@1.txt"
```
- 此处file的只能上传当前文件夹内的文件,且使用`@`标识符,
-- 能否上传其它目录的文件呢???
-- 能否上传文件夹呢???
## 下载问题
- 下载:
 ```
wget http://IP:port/shared/要下载的文件名
curl -O http://IP:port/shared/要下载的文件名
```
能否下载文件夹???
## 首页通告栏
说明放在了 chfs.ini 文件里,并没有在页面进行说明,找起来稍微麻烦了点.

**Comment by docblue** [comment]
PART1 据我所知不支持，可以一个个上传或打包后上传；可以指定目标目录
PART2 下载文件夹只需要在目录名后面加上.zip后缀即可，如/shared/jack/ebooks.zip
PART3 OK，随后补上
